### ISSUE TITLE
Proof-of-Stake Algorithm

### ISSUE THREAD

**Issue by Romulus10** [Romulus10/BlockchainSimulator#19]
Implementation of Proof-of-Stake consensus.

**Comment by Romulus10** [comment]
I'm assigning all of us to this, since it's really the bulk of the worst of what we need to get finished before we can say this thing is working. I'm working on it in [proof_of_stake](https://github.com/Romulus10/BlockchainSimulator/tree/proof_of_stake).

**Comment by thejdubs** [comment]
completed
