### ISSUE TITLE
Angular UI

### ISSUE THREAD

**Issue by Romulus10** [Romulus10/BlockchainSimulator#21]

**Comment by Romulus10** [comment]
I started the client-facing API, we should start working through tying the API and UI together.

**Comment by lenguyentri1999** [comment]
@Romulus10 Sounds good, let's do that. What time is the meeting today?

**Comment by Romulus10** [comment]
@lenguyentri1999 I've got endpoints together for getting data from the blockchain. I doubt whether they'll work immediately, but we should start tying everything together.

**Comment by Romulus10** [comment]
Had to leave the call - I'll follow any conversations on issues/PRs and do some contributions to the design doc.

**Comment by thejdubs** [comment]
no feedback on invalid stake amount,
no immediate feedback on staking, refresh required.
display data in block missing
suggested:
show more data in the transaction

**Comment by Romulus10** [comment]
> by #83
> no feedback on invalid stake amount,
> no immediate feedback on staking, refresh required.
> display data in block missing
> suggested:
> show more data in the transaction

@lenguyentri1999 I think this plus showing whether a block is valid are all we need to do.

**Comment by thejdubs** [comment]
add block numbering to "Block" header. ie Block 0, Block 1

**Comment by thejdubs** [comment]
remove add block button (or does this do something?)

**Comment by Romulus10** [comment]
> remove add block button (or does this do something?)

I don't think it does. @lenguyentri1999 can you confirm?

**Comment by lenguyentri1999** [comment]
> > remove add block button (or does this do something?)
> 
> I don't think it does. @lenguyentri1999 can you confirm?

It doesn't do anything, I'll remove it in a new branch.

**Comment by thejdubs** [comment]
by #90 
block number is outside of block container
think it should be changed in:
Frontend\ionic-app\src\app\components\block\block.component.html line 4

view transactions doesnt fire event

**Comment by Romulus10** [comment]
> by #90
> block number is outside of block container
> think it should be changed in:
> Frontend\ionic-app\src\app\components\block\block.component.html line 4
> 
> view transactions doesnt fire event

Opened new issues #94 #92 #91 for these.
